### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by parabol0ide** [L-Dot/Letterboxd-list-scraper#1]
Some unicode characters are not recognized and, when this happens, it stops writing the csv.
`UnicodeEncodeError: 'charmap' codec can't encode character '\u014d' in position 556: character maps to <undefined>`

**Comment by F4400** [comment]
I had the same Error and same '\u014d' symbol. Checking the movie in the csv where it failed it was Yasujirō Ozus Tokyo Story. So the `ō` was the problem.

In the file "csv_writer.py" I changed this part. Other changes I made are `newline=''` as param so that not every second line is empty and I chose a different delimiter because some movies have a `,` in the title.

```
Old:
    with open(f'{list_name}.csv', 'w') as f:
        write = csv.writer(f)

New:
    with open(f'{list_name}.csv', 'w', newline='', encoding="utf-8") as f:
        write = csv.writer(f, delimiter =";")
```
If you want to open the file in Excel I wouldn't recommend to open it directly but go to the "Data" Tab and import the CSV file. This way you can set the right encoding. Otherwise the `ō` may change to a `Å`.
