### ISSUE TITLE
The CSV files generated from these lists are almost empty (more details inside)

### ISSUE THREAD

**Issue by champorado86** [L-Dot/Letterboxd-list-scraper#12]
Hi, first off, hats off to you for creating this scraper. I'm trying to build a dataset from the Letterboxd users I follow and this has been a timesaver. I was just manually scraping LOL :)

I ran into an issue with [this link](https://letterboxd.com/troythrace/films/rated/5/
) and [this link](https://letterboxd.com/minwon/films/rated/5/) as both of them return almost empty CSV files. I've tried other links before with a similar option and they came out OK. The first one should have returned a CSV with **87 titles** and the second one should return **145 titles**. What got generated are 1kb CSV files with only 1 title each. I also noticed there was no notification of **"Written to xxx-film.csv"** either.

**I'd like to understand what's causing the issues for these 2 particular links.** Again, thank you for creating this scraper tool and I hope you have other development plans for this in the future.

**Comment by AntoniGnas** [comment]
Is it just those two or any url that is linked to "watched" section in someone's profile? I think the issue here is that lists, watchlists etc works on pretty much te same html code, and "watched" section does not. But I've got to say I'm no expert on the matter. But returing to my first question, if it works with different accounts I have absolutely not the slightest idea.

**Comment by L-Dot** [comment]
Hi! Glad the project is of use to you 😄

I had a quick look and this bug seems to be a _very_ specific case where the **first** film in the list is **unreleased** (e.g. https://letterboxd.com/film/furiosa-a-mad-max-saga/ and https://letterboxd.com/film/wicked-2024/ in your case). Because it is unreleased, there are no official ratings and the histogram stats page `https://letterboxd.com/csi/film/{title}/rating-histogram/` is empty.

Scraping is done correctly, but the program crashes during writeout as no `½,★,★½, etc.` columns were created for the unreleased film. Moreover, because the writeout function extracts the CSV/JSON header from the first film entry, this only happens when the unreleased film is the first entry in the list. Congrats on finding this very specific bug!

Anyway a clumsy oversight on my part, but I did not realise that you could add unreleased films to lists (TIL 😃). I have added a fix to the program and your lists should now scrape correctly.

**Comment by L-Dot** [comment]
I've added the fix in [v2.1.0](https://github.com/L-Dot/Letterboxd-list-scraper/releases/tag/v2.1.0) so I'll close this issue for now.

**Comment by champorado86** [comment]
Thank you! That was fast :)
